# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

env:
  global:
    - GO111MODULE=on
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config

jobs:
  include:
    - stage: Controller API
      language: go
      go:
        - 1.12.x
      dist: xenial
      sudo: required
      services:
        - docker
      before_install:
        # golangci-lint
        - curl -sSfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
        # Ginkgo
        - go get -u github.com/onsi/ginkgo/ginkgo
      before_script:
        # Get project dependencies
        - go mod download
      script:
        - make lint kubectl-install minikube-install minikube-start minikube-wait test
    - stage: Controller UI
      language: node_js
      node_js:
        - "lts/*"
      before_script:
        - cd ui/controller
        - npm install -g yarn
      script:
        - yarn install
        - yarn build
        - yarn test
    - stage: CUPs UI
      language: node_js
      node_js:
        - "lts/*"
      before_script:
        - cd ui/cups
        - npm install -g yarn
      script:
        - yarn install
        - yarn build
        - yarn test
