# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  name: bbdev-config
data:
  fpga_bbdev.cfg: |
    [MODE]
    pf_mode_en = 0
    
    [UL]
    bandwidth = 3
    load_balance = 128
    vfqmap = 16,16,0,0,0,0,0,0
    
    [DL]
    bandwidth = 3
    load_balance = 128
    vfqmap = 16,16,0,0,0,0,0,0
    
    [FLR]
    flr_time_out = 610
